// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gplltbkfconqjcyfsnel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwbGx0YmtmY29ucWpjeWZzbmVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDM0NzIsImV4cCI6MjA2NTU3OTQ3Mn0.w-2tRL_oe8hRIpoTwY-idU1OrPQhD5qIXRQropTN3sU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);